// This file was auto-generated by ML.NET Model Builder. 

using System;
using Hello_mlML.Model;

namespace Hello_mlML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                YearsExperience = 1.1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");
            Console.WriteLine($"YearsExperience: {sampleData.YearsExperience}");
            Console.WriteLine($"\n\nPredicted Salary value {predictionResult.Prediction} \nPredicted Salary scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
