// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Hello_mlML.Model
{
    public class ModelInput
    {
        [ColumnName("YearsExperience"), LoadColumn(0)]
        public float YearsExperience { get; set; }


        [ColumnName("Salary"), LoadColumn(1)]
        public string Salary { get; set; }


    }
}
